// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// FILE GENERATED BY FLUTTERFIRE CLI. DO NOT MODIFY.
//
// This file is a placeholder and contains EXAMPLE credentials. To generate the
// real `firebase_options.dart` for your project, please follow these steps:
//
// 1. Install the Firebase CLI:
//    npm install -g firebase-tools
//
// 2. Log in to your Firebase account:
//    firebase login
//
// 3. Activate the FlutterFire CLI:
//    dart pub global activate flutterfire_cli
//
// 4. Navigate to your Flutter project root directory in the terminal:
//    cd C:\Users\Kabum\Desktop\battery_buddy_flutter
//
// 5. Run the configure command:
//    flutterfire configure
//
// This will automatically generate the correct `firebase_options.dart` file
// with your project's unique credentials.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example platform specific FirebaseOptions configuration.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2fXq8oSjwl5KjrX2hj4IZ-NYxWYHG2U8',
    appId: '1:577036011593:android:a4f15285648f9f973e1798',
    messagingSenderId: '577036011593',
    projectId: 'batterybuddy-3fe86',
    storageBucket: 'batterybuddy-3fe86.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMKc42PJ5_Iztm6zruI3QND6uv2t5ZaEg',
    appId: '1:577036011593:web:4afab6b249ead3923e1798',
    messagingSenderId: '577036011593',
    projectId: 'batterybuddy-3fe86',
    authDomain: 'batterybuddy-3fe86.firebaseapp.com',
    storageBucket: 'batterybuddy-3fe86.firebasestorage.app',
    measurementId: 'G-EQJW5BPCW9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDos1SnegHixqtLJSBlL5G8cOTVIM3MSns',
    appId: '1:577036011593:ios:8f84c6fe6a8547863e1798',
    messagingSenderId: '577036011593',
    projectId: 'batterybuddy-3fe86',
    storageBucket: 'batterybuddy-3fe86.firebasestorage.app',
    iosClientId:
        '577036011593-sqm1g5o74lm0j9ln43ttj28qfphvf7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.batteryBuddyFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDos1SnegHixqtLJSBlL5G8cOTVIM3MSns',
    appId: '1:577036011593:ios:8f84c6fe6a8547863e1798',
    messagingSenderId: '577036011593',
    projectId: 'batterybuddy-3fe86',
    storageBucket: 'batterybuddy-3fe86.firebasestorage.app',
    iosClientId:
        '577036011593-sqm1g5o74lm0j9ln43ttj28qfphvf7qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.batteryBuddyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMKc42PJ5_Iztm6zruI3QND6uv2t5ZaEg',
    appId: '1:577036011593:web:3f577b14887326493e1798',
    messagingSenderId: '577036011593',
    projectId: 'batterybuddy-3fe86',
    authDomain: 'batterybuddy-3fe86.firebaseapp.com',
    storageBucket: 'batterybuddy-3fe86.firebasestorage.app',
    measurementId: 'G-C6RSXKWE00',
  );
}
